### ISSUE TITLE
Allow image re-use

### ISSUE THREAD

**Issue by knkiers** [quantum-bits/capernaum#65] opened 2020-03-07 15:18 UTC
From Steve:
> Images cannot be used in more than one letter, apparently. I need to rename the images on the drive and copy them up to capernaum with the  new name.

...maybe this was done on purpose, but I think it may be a bug...(?)

**Comment by nurkkala** [comment] 2020-04-16 21:33
Duplicate of #62

**Closed by nurkkala** 2020-04-16 21:33 UTC
